version: "3.9"

services:
  asmo:
    container_name: asmodeus
    image: asmodeus
    environment:
      ASMO_CONFIG_FILE: 'config.yaml'
      ASMO_HTTP_PORT: 9090
    expose:
      - "8901-8903"
    ports:
      - "8352-8354:8901-8903"
      - "9099:9090"
    volumes:
      - type: bind
        source: ./example_config.yaml
        target: /usr/app/config.yaml
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9999:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
    - type: bind
      source: ./prometheus/prometheus.yml
      target: /etc/prometheus/prometheus.yml
    depends_on:
      - asmo

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
    - type: bind
      source: ./grafana/grafana.ini
      target: /etc/grafana/grafana.ini
    - type: bind
      source: ./grafana/provisioning
      target: /etc/grafana/provisioning
    - type: bind
      source: ./grafana/dashboards
      target: /var/lib/grafana/dashboards
    depends_on:
      - prometheus


