forwarders:
  - inputPort: 8901
    outputPort: 5432
    outputIp: 'postgres_db'
  - inputPort: 8902
    outputPort: 5432
    outputIp: 'postgres_db'
  - inputPort: 8903
    outputPort: 5432
    outputIp: 'postgres_db'